import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // カーネルコードのサイドバー
  kernelSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
};

export default sidebars;